---
title: "Biobank dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    source_code: embed
    theme: 
      version: 4
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(knitr)
library(DT)
library(rpivotTable)
library(ggplot2)
library(plotly)
library(dplyr)
library(openintro)
library(highcharter)
library(ggvis)
library(sqldf)
library(data.table)
library(shiny)
library(spData)
library(sf)
library(leaflet)
library(reshape)
library(tidyr)
library(RColorBrewer)

```


```{r}
dataset <- read.csv("dataset.csv",header = TRUE)

specimen_type <- dataset %>% count(Specimen_Type)

#specimen_status <- dataset %>% count(Specimen_Pathological.Status)


Total_plasma <- specimen_type[specimen_type$Specimen_Type == 'Plasma' , 'n']
Total_Serum <- specimen_type[specimen_type$Specimen_Type == 'Serum', 'n']
Total_Buffy_Coat <- specimen_type[specimen_type$Specimen_Type == 'Buffy_Coat', 'n']
Total_Fresh_Tissue <- specimen_type[specimen_type$Specimen_Type == 'Fresh_Tissue' , 'n']

Total_Project <- length(unique(dataset$Project))
Total_Patients <-length(unique(dataset$Participant_PPID))

gender_df <- dataset[!duplicated(dataset[, c("Participant_PPID", "Participant_Gender")]), ]
                      

```

```{r}
mycolors <- c("blue", "#FFC125", "darkgreen", "darkorange")
```

Overall Data Visualization
=====================================

Row
-------------------------------------

### Summary dashboard

```{r}
valueBox(paste("Biobank"),
         color = "warning")
```

### Total Project

```{r}
valueBox(Total_Project,
         icon = 'fa-tasks')
```

### **Total Patients**

```{r}
valueBox(Total_Patients,
         icon = 'fa-users')

```

### Plasma

```{r}
valueBox(Total_plasma,
         icon = 'fa-tint')
```

### Serum

```{r}
valueBox(Total_Serum,
         icon = 'fa-burn')
```

### Buffy coat

```{r}
valueBox(Total_Buffy_Coat,
         icon = 'fa-vial')
```

### Fresh Tissue

```{r}
valueBox(Total_Fresh_Tissue,
         icon = 'fa-diagnoses')
```

Row
-------------------------------

### Pie chart from Specimen_Type

```{r}

dataset %>%
  count(Specimen_Type) %>% 
  plot_ly(labels = ~Specimen_Type, values = ~n, marker = list(colors = c("#FECCC9", "#FEE7C9", "#C9E0FE", "#C9FECD"), line = list(color = '#FFFFFF', width = 1)), type = "pie")


``` 



### Pie chart from Specimen_Pathological.Status 

```{r}

dataset %>%
  count(Specimen_Pathological.Status) %>% hchart("pie", hcaes(x= Specimen_Pathological.Status, y=n), name = "Pie chart from Specimen_Pathological.Status ")

# dataset %>%
#   count(Specimen_Pathological.Status) %>%
#   plot_ly(labels = ~Specimen_Pathological.Status, values = ~n, marker = list(colors = c("#FEE7C9", "#C9FECD", "#E2E0FE"), line = list(color = '#FFFFFF', width = 1)), type = "pie")

```

### Piecharts of gender
```{r}
dataset %>%
  count(Participant_PPID, Participant_Gender) %>%
  plot_ly(labels = ~Participant_Gender, marker = list(colors = c("#C9E0FE", "#FECCC9"), line = list(color = '#FFFFFF', width = 1)), type = "pie")

```


Row
------------------------------------
### #line graph specimen type in each year

```{r}
dataset %>%
  count(Year, Specimen_Type) %>% 
  dplyr::rename(sum_value = n) %>%
  plot_ly(x = ~Year, y = ~sum_value, color = ~Specimen_Type, type = "scatter", mode = "lines+markers")

```

### barchart each specimen type group by project
```{r}

dataset %>% count(Project,Specimen_Type) %>%
  dplyr::rename(sum_value = n) %>%
  hchart('column', hcaes(x = Project, y = sum_value, group = Specimen_Type), dataLabels = list(
  enabled = TRUE)) %>% hc_colors(c("#FC9D96", "#FCD096", "#B5D4FC", "#A2E2A6"))

```

Query
========================================


```{r}

df <- sqldf("SELECT Year,Project,COUNT(*) AS Total_samples,COUNT(DISTINCT Participant_PPID) AS Total_patients,
            SUM(CASE WHEN Specimen_Type = 'Plasma' THEN 1 ELSE 0 END) as Plasma,
            SUM(CASE WHEN Specimen_Type = 'Serum' THEN 1 ELSE 0 END) as Serum,
            SUM(CASE WHEN Specimen_Type = 'Buffy_Coat' THEN 1 ELSE 0 END) as Buffy_Coat,
            SUM(CASE WHEN Specimen_Type = 'Fresh_Tissue' THEN 1 ELSE 0 END) as Fresh_Tissue,
            SUM(CASE WHEN [Specimen_Pathological.Status] = 'Non-Malignant' THEN 1 ELSE 0 END) as Normal_Tissue,
            SUM(CASE WHEN [Specimen_Pathological.Status] = 'Malignant' THEN 1 ELSE 0 END) as Diseased_Tissue,
            SUM(CASE WHEN [Specimen_Pathological.Status] = 'Not Specified' THEN 1 ELSE 0 END) as Not_Specified
            FROM dataset
            GROUP BY Year,Project
            ");

data_melt <-melt(df %>% select(Year,Project,Plasma,Serum,Buffy_Coat,Fresh_Tissue),id = c("Year","Project"))

```


Column {.sidebar data-width=200}
-------------------------------------------------------------------
```{r}

selectInput(inputId="year", label = "Select Year:", choices = c(unique(dataset$Year),"Select All"))

selectInput(inputId="project", label = "Select Project:", choices = c(unique(dataset$Project),"Select All"))

```


```{r}
#create function to sub query from original dataset, output of this function is the input of below Valuebox
sub_dataset <- reactive({
   # Filter data based on selected year
    if (input$year == "Select All") {
      dataset<- dataset
    }
    if (input$year != "Select All") {
      dataset<- filter(dataset, Year == input$year)
    }
    
    # Filter data based on selected project
    if (input$project == "Select All") {
      dataset <- dataset
    }
  
    if (input$project != "Select All") {
      dataset <- filter(dataset, Project == input$project)
    }
  return(dataset)
  
})
```


Row
-------------------------------------

### Summary dashboard

```{r}
valueBox(paste("Query:Biobank"),
         color = "warning")
```

### Total Project

```{r}
renderValueBox({
  
  TTproject <- length(unique(sub_dataset()$Project))
  valueBox(TTproject,
         icon = 'fa-tasks')
})

```

### **Total Patients**

```{r}
renderValueBox({

  TTpatients <-length(unique(sub_dataset()$Participant_PPID))
  
  valueBox(TTpatients,
         icon = 'fa-users')
  
})


```

### Plasma

```{r}

renderValueBox({
  
  TTplasma <- table(sub_dataset()$Specimen_Type)['Plasma']
  
  valueBox(TTplasma,
         icon = 'fa-tint')
  
})

```

### Serum

```{r}
renderValueBox({

  TTserum <- table(sub_dataset()$Specimen_Type)['Serum']
  
  
  valueBox(TTserum,
         icon = 'fa-burn')
})

```

### Buffy coat

```{r}
renderValueBox({
  
  TTbuffycoat <- table(sub_dataset()$Specimen_Type)['Buffy_Coat']
  
  valueBox(TTbuffycoat,
         icon = 'fa-vial')
  
})

```

### Fresh Tissue

```{r}
renderValueBox({
  
  TTfreshtissue <- table(sub_dataset()$Specimen_Type)['Fresh_Tissue']
  
  valueBox(TTfreshtissue,
         icon = 'fa-diagnoses')
  
})

```


Column {data-width=400}
-------------------------------------------------------------------

### **Box plot** shows the relationship between categorical and numeric variables
```{r}

renderHighchart( {
    
    # Error message for when user has filtered out all data
    validate (
      need(nrow(sub_dataset()) > 0, "No data found. Please make another selection.")
    )
    
  
  specimens <- sub_dataset() %>% group_by(Specimen_Type) %>% tally()
    
    # Bar chart
    specimens %>% hchart('column', hcaes(x = Specimen_Type, y = n, color = Specimen_Type))

  })

```

### Pie chart
```{r}
renderPlot( {
  
  gender_df <- sub_dataset()[!duplicated(sub_dataset()[, c("Participant_PPID", "Participant_Gender")]), ]
    
    # Error message for when user has filtered out all data
    validate (
      need(nrow(sub_dataset()) > 0, "No data found. Please make another selection.")
    )
    
    # Get sum of each gender
    gend <- as.data.frame(table(gender_df$Participant_Gender))
  gend <- gend %>% mutate(per=Freq/sum(Freq)) %>% arrange(desc(Var1))
  gend$label <- scales::percent(gend$per)
    
    #plot Pie chart
    ggplot(data =gend)+geom_bar(aes(x='',y=per,fill=Var1), stat='identity', width = 1)+coord_polar("y",start=0)+ theme_void()+geom_text(aes(x=1,y=cumsum(per)- per/2,label=label))+ggtitle("Gender Pie chart")
    #ggplot(gend, aes(x="", y=Freq, fill=Var1)) +
     # geom_bar(stat="identity", width=1) +
      #coord_polar("y", start=0)

  })

```

Column {data-width=400}
-------------------------------------------------------------------

### show summary table
```{r}

 renderDataTable({
    
    # Filter data based on selected Style
    if (input$year == "Select All") {
      data_melt <- data_melt
    }
   
    if (input$year != "Select All") {
      data_melt <- filter(data_melt, Year == input$year)
    }
    
    # Filter data based on selected Country
    if (input$project == "Select All") {
      data_melt <- data_melt
    }
    
    if (input$project != "Select All") {
      data_melt <- filter(data_melt, Project == input$project)
    }
    
    # Hide table when user has filtered out all data
    validate (
      need(nrow(data_melt) > 0, "")
    )
    
    data_melt[,]
    
  })
```



Table
=========================================

```{r}
DT::datatable(df, options = list(
  bPaginate = FALSE
))
```



User Guide
========================================

Credit by: 

Confidential: Public




